### ISSUE TITLE
Rope type completeness ratchet can be simplified if pyright-type-completeness implements missing py.typed handling

### ISSUE THREAD

**Issue by smheidrich** [smheidrich/snoozed-todos#5]
- https://github.com/Bibo-Joshi/pyright-type-completeness/issues/5
- https://github.com/python-rope/rope/pull/799

**Comment by smheidrich** [comment]
@SnoozeThis https://github.com/Bibo-Joshi/pyright-type-completeness/issues/5

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/mfZowuiGz3U) I will wait until https://github.com/Bibo-Joshi/pyright-type-completeness/issues/5 is closed and then reassign to you.

**Comment by SnoozeThis** [comment]
Resolved.

**Comment by smheidrich** [comment]
Postponed
